version: '3'
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    networks:
      - mynetwork
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
  #     ME_CONFIG_BASICAUTH: false

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3003:3003"
    depends_on:
      - db
    networks:
      - mynetwork
    # volumes:
    #   - ./backend:/usr/src/app
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    # volumes:
    #   - ./frontend:/usr/src/app
    restart: always

  thirdparty:
    build: ./third-party-api
    container_name: thirdparty
    ports:
      - "3030:3030"
    networks:
      - mynetwork
    # volumes:
    #   -  ./third-party-api:/usr/src/app
    restart: always

# volumes:
#   dbdata:
#   backenddata:
#     driver_opts:
#       o: "bind"
#       type: none
#       device: ./backend
#   frontenddata:
#     driver_opts:
#       o: "bind"
#       type: none
#       device: ./frontend
#   thirdpartydata:
#     driver_opts:
#       o: "bind"
#       type: none
#       device: ./third-party-api


networks:
  mynetwork:
    driver: bridge
    name: BookstoreNetwork

  